### ISSUE TITLE
Would you consider adding timezone support to DateTime typecasting code?

### ISSUE THREAD

**Issue by asppsa** [deepfryed/swift-db-mysql#4]
This arises because I am using Sequel and tried to switch from using the mysql2 adapter to the swift adapter.  I found that all appeared to work, except that all DateTime objects had a UTC timezone, whereas what I wanted was for them to be treated as "local" times.   In sequel this is handled by telling it the timezone that the database is expected to be running in (`database_timezone`), as well as the timezone that the application is running in (`local_timezone`).

We've now patched the sequel swift adapter to do this timezone managing for us (see jeremyevans/sequel#946), but @jeremyevans has pointed out that the best place for this would be in the driver code itself (i.e. here), the same as what mysql2 does (see https://github.com/brianmario/mysql2/blob/c32f0f35c776eeb2163d13cb7751168980771416/README.md#timezones)

As such I'm writing this to ask if you'd consider implementing this here.

Cheers!

**Comment by deepfryed** [comment]
Sure, no worries.

Under bit of time pressure at work but will have a look in the next couple of days.

**Comment by deepfryed** [comment]
I'm having second thoughts about this as I think about it.  MySQL does not have inbuilt support for timezones so storing timestamps in UTC is good practice.

 1. One option which might be faster (in terms of doing work in Ruby) is to use `CONVERT_TZ` function in MySQL

```ruby
db.execute("select convert_tz(now(), 'SYSTEM', 'UTC') as time")
```
That assumes the database stores timestamps in system timezone and converts it to UTC using the timezone information handling DST conversions. You can convert that to local time by calling the `to_time` method.

2. Using a full blown timezone library that handles this on the adapter side so you can specify timezone labels to force from and to timezones. This will make the code path much slower but will give you the most flexibility keeping the api clean. I'm going to put some thought into this and build something that allows better integration across the different swift database adapters.

e.g.

```ruby
db = Swift::DB::Mysql.new(db: "test", parser: {datetime: Swift::DB::DateTimeConverter.new("UTC", "America/Chicago")})
```

**Comment by deepfryed** [comment]
@asppsa Could you give https://github.com/deepfryed/swift-db-timezone a try, it's a first revision of what I think is more saner than just assuming utc or local timezone like mysql2 does. Thanks!

**Comment by asppsa** [comment]
Hi, thanks for your work on this.  I shall check it out ASAP!

**Comment by jeremyevans** [comment]
@deepfryed swift-db-timezone looks pretty good, but it would be great if the timezones could be specified on a per-query basis.  This is necessary to support thread-local timezones, which are pretty common if you are using a threaded webserver and converting all times to the timezone of the user related to the request.  As you are only using the timezones when processing the results of queries, being able to specify them when issuing the query or before retrieving the results of the query should hopefully be simple and not complicate things unnecessarily.

**Comment by deepfryed** [comment]
> it would be great if the timezones could be specified on a per-query basis. This is necessary to support thread-local timezones

Yeah that's not hard to do, will roll it in. The way we use the adapters in Swift is create an instance of adapter per thread, so adapter pool is thread safe. Not sure if that is bullet proof but has worked well in the past.

**Comment by deepfryed** [comment]
see https://github.com/deepfryed/swift-db-timezone/blob/master/test/test_timezone.rb#L27

**Comment by deepfryed** [comment]
Small world @asppsa  :wink:
