### ISSUE TITLE
How do I connect with my swift project.

### ISSUE THREAD

**Issue by pilotkid** [deepfryed/swift-db-mysql#6]
Hello, I am rather new to swift so please accept my apologies in advance for this ridiculous question. 

How do I add your library into Xcode? How do you import it into your view controller? 

Thanks,
Marcello B.

**Comment by shanna** [comment]
This is a database driver for Swift the Ruby ORM (2010) not Swift Apples new (2014) programming language.

I don't know of an ORM for Apples Swift that supports MySQL sorry.
